### PR TITLE
Update mrf_insert to make it work with gdal v3, including changes in MRF

### PR DESCRIPTION
**Pull request by lucianpls**

### CODE REVIEW

**Comment by jtroberts** [comment]
Is this still compatible with GDAL versions prior to 3?

**Comment by lucianpls** [comment]
> 
> 
> Is this still compatible with GDAL versions prior to 3?

No, the changes in MRF check version 3, and even that check is too loose.
It should be pretty easy to make it work, the only breaking change is the name of the MRFDataset (used to be GDALMRFDataset).

You could leave this pull request open until you're ready to commit to 3.x.
If you do leave it pending, look at the nearNB bug fix, that's the only significant change.

**Comment by lucianpls** [comment]
Or if you still need them, maybe we should keep the 2.x (or even 1.x) in a branch, so the master works against the current GDAL?

**Comment by jtroberts** [comment]
That's a good idea. I think we want branches for specific versions of GDAL while keeping master current with the latest GDAL version. I created separate branches for the versions that we're still using. We probably want to pull in the nearNB bug into 2.4.4 unless we decide to just jump ahead to v3.x.

We should leave the PR open until we've updated the GDAL references to v3 and test so that our builds aren't broken.

**Pull request merged**
